<ivy-module version="2.0">
    <!--
        © Copyright IBM Corporation 2014, 2016.
        This is licensed under the following license.
        The Eclipse Public 1.0 License (http://www.eclipse.org/legal/epl-v10.html)
        U.S. Government Users Restricted Rights:  Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
    -->
    <info organisation="com.ibm.urbancode" module="dependencies"/>
    <configurations>
        <conf name="default" description="Jars used during runtime"/>
        <conf name="build" description="Jars used during build"/>
        <conf name="test" description="Jars used during testing"/>
    </configurations>
    <dependencies>
        <!-- http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.ibm.urbancode.plugins%22 -->
        <dependency org="com.ibm.urbancode.plugins" name="groovy-plugin-utils" rev="1.0" transitive="false" conf="default->default"/>
        <!-- https://mvnrepository.com/artifact/commons-codec/commons-codec -->
        <dependency org="commons-codec" name="commons-codec" rev="1.3" transitive="false" conf="default->default"/>
        <!-- https://mvnrepository.com/artifact/commons-httpclient/commons-httpclient -->
        <dependency org="commons-httpclient" name="commons-httpclient" rev="3.1" transitive="false" conf="default->default"/>
        <!-- https://mvnrepository.com/artifact/commons-logging/commons-logging -->
        <dependency org="commons-logging" name="commons-logging" rev="1.1" transitive="false" conf="default->default"/>
        <!-- https://mvnrepository.com/artifact/xml-apis/xml-apis -->
        <dependency org="xml-apis" name="xml-apis" rev="1.4.01" transitive="false" conf="default->default"/>
        <!-- https://mvnrepository.com/artifact/xml-resolver/xml-resolver -->
        <dependency org="xml-resolver" name="xml-resolver" rev="1.2" transitive="false" conf="default->default"/>
    </dependencies>
</ivy-module>
